### ISSUE TITLE
虚拟障碍（interactive markers）相关问题

### ISSUE THREAD

**Issue by Octalivia** [gsc07/autolabor_simulation#2]
我不希望再rviz中右击勾选apply来将其添加到map中，而希望在launch文件/源码中直接apply，请问应该怎么更改？以及初始位置是否能通过源码/launch文件更改?

**Comment by gsc07** [comment]
虚拟障碍物设置是通过调用simualtion_stage节点中的obstacle_handle服务实现的，通过这个服务可以用来在地图中设置障碍物，移动障碍物以及删除障碍物。其中apply选中对应新增障碍物，取消选中对应删除障碍物，如果通过程序可以实现障碍物的动态移动。您可以在launch中删除simulation_object节点，自己写一个节点调用obstacle_handle服务来操控障碍物信息。

**Comment by gsc07** [comment]
> 我不希望再rviz中右击勾选apply来将其添加到map中，而希望在launch文件/源码中直接apply，请问应该怎么更改？以及初始位置是否能通过源码/launch文件更改?

虚拟障碍物设置是通过调用simualtion_stage节点中的obstacle_handle服务实现的，通过这个服务可以用来在地图中设置障碍物，移动障碍物以及删除障碍物。其中apply选中对应新增障碍物，取消选中对应删除障碍物，如果通过程序可以实现障碍物的动态移动。您可以在launch中删除simulation_object节点，自己写一个节点调用obstacle_handle服务来操控障碍物信息。

**Comment by Octalivia** [comment]
操控障碍物的功能在您的程序中已经很完善了，我的意思是在构造函数中是否可以直接添加障碍物到地图中？因为我在构造函数中添加了如下代码
`lidar_simulation::Obstacle msg;
  msg.request.obstacle_id = obstacle_id_;
  msg.request.type = lidar_simulation::Obstacle::Request::NEW;
  msg.request.vertex = obstacle_footprints_;
  msg.request.transform[0] = poseX_;
  msg.request.transform[1] = poseY_;
  msg.request.transform[2] = 0; 
  client_.call(msg); 
  transform_flag_ = true;
  if (transform_flag_){
    msg.request.type = lidar_simulation::Obstacle::Request::TRANSFORM;
    client_.call(msg);`
但是出现了报错
`[ERROR] [1565106066.176099534]: Service call failed: service [/obstacle_handle] responded with an error: No specified obstacle`

**Comment by Octalivia** [comment]
操控障碍物的功能在您的代码中已经很完善了，我是想改变障碍物的初始位置。当我在SimulationObject的构造函数中添加如下代码编译后，apply后发现激光雷达并不能正确扫描到它，如果您有时间的话麻烦指导一下应该如何更改
`interactive_marker_.pose.position.x = 10.0;
  interactive_marker_.pose.position.y = 10.0;
marker_.pose.position.x = 10.0;
  marker_.pose.position.y = 10.0；
`

**Comment by gsc07** [comment]
> 操控障碍物的功能在您的代码中已经很完善了，我是想改变障碍物的初始位置。当我在SimulationObject的构造函数中添加如下代码编译后，apply后发现激光雷达并不能正确扫描到它，如果您有时间的话麻烦指导一下应该如何更改
> `interactive_marker_.pose.position.x = 10.0; interactive_marker_.pose.position.y = 10.0; marker_.pose.position.x = 10.0; marker_.pose.position.y = 10.0； `

如果需要改变障碍物的初始位置，最简单的方法就是在launch文件中，修改object_footprints参数，这个参数表示初始状态下障碍物所在位置的轮廓的坐标，比如你想将障碍物位置偏移（10, 10），可以直接在object_footprints的每个x,y坐标分别加10。其中object_footprints参数是一个二维数组，格式是
[[物体1]， [物体2]，[物体3]]
其中[物体1] 这个里面具体数值表示[轮廓顶点1的x坐标，轮廓顶点1的y坐标，轮廓顶点2的x坐标，轮廓顶点2的y坐标]
希望能帮到您

**Comment by Octalivia** [comment]
您的建议解决了我的一个问题，还有个问题是我希望object的初始状态是被apply的，所以我在run()的末尾添加了以下代码, 但是没有起效，请问应该怎么改呢
`   autolabor_simulation_stage::Obstacle msg;
    msg.request.obstacle_id = object_id_;
    msg.request.type = autolabor_simulation_stage::Obstacle::Request::NEW;
    msg.request.transform[0] = 0.0;
    msg.request.transform[1] =  0.0;
    msg.request.transform[2] =  0.0;
    client_.call(msg);`

**Comment by gsc07** [comment]
> 您的建议解决了我的一个问题，还有个问题是我希望object的初始状态是被apply的，所以我在run()的末尾添加了以下代码, 但是没有起效，请问应该怎么改呢
> ` autolabor_simulation_stage::Obstacle msg; msg.request.obstacle_id = object_id_; msg.request.type = autolabor_simulation_stage::Obstacle::Request::NEW; msg.request.transform[0] = 0.0; msg.request.transform[1] = 0.0; msg.request.transform[2] = 0.0; client_.call(msg);`

我大概看了一下大概问题是在run这个函数里面ros::spin()是阻塞的，后面的语句估计没办法执行，如果在ros::spin()之前放这些语句可有由于stage结点服务没开导致call方法阻塞，常用办法就是用个定时器去设置，我大概给你改了一版在附件中，添加了一个default_apply参数，只要设置参数为true，就可以默认被apply的
[autolabor_simulation_object.zip](https://github.com/gsc07/autolabor_simulation/files/3475847/autolabor_simulation_object.zip)
