### ISSUE TITLE
make html fail

### ISSUE THREAD

**Issue by guzhaoyuan** [gsc07/autolabor_simulation#4]
I am using ubuntu 18.04. I installed python3 and python3-sphinx.
When I run `make html`, it pops the following error.
```
sphinx-build -b html -d build/doctrees   source build/html
Traceback (most recent call last):
  File "/usr/bin/sphinx-build", line 14, in <module>
    from sphinx import main
ImportError: cannot import name 'main'
Makefile:56: recipe for target 'html' failed
make: *** [html] Error 1
```

**Comment by Jackey-Huo** [comment]
@guzhaoyuan I did not encounter the error when building it. Would you mind to provide more information about your sphinx-build tool?
e.g. my sphinx-build version is
```bash
$ sphinx-build --version
sphinx-build 2.3.1
```

**Comment by guzhaoyuan** [comment]
After fast-forward to the lasted commit fc011e05711385ae941e4c97d10e3f4a44f6ad2f. The compile passes.

**Comment by Jackey-Huo** [comment]
great ;)
